import express from "express";import cors from "cors";import dotenv from "dotenv";import {connectDB} from "./config/db.js";
import authRoutes from "./routes/authRoutes.js";import applicationRoutes from "./routes/applicationRoutes.js";import memberRoutes from "./routes/memberRoutes.js";import paymentRoutes from "./routes/paymentRoutes.js";import donationRoutes from "./routes/donationRoutes.js";import financeRoutes from "./routes/financeRoutes.js";import contentRoutes from "./routes/contentRoutes.js";import expenseRoutes from "./routes/expenseRoutes.js";
import receiptRoutes from "./routes/receiptRoutes.js";import auditLogRoutes from "./routes/auditLogRoutes.js";
dotenv.config();const app=express();const port=process.env.PORT||5000;
app.use(cors({origin:process.env.CLIENT_URL||"http://localhost:5173"}));app.use(express.json());
app.get("/api/health",(req,res)=>res.json({success:true,message:"Ganesh Community API is running"}));
app.use("/api/auth",authRoutes);app.use("/api/member-applications",applicationRoutes);app.use("/api/members",memberRoutes);app.use("/api/payments",paymentRoutes);app.use("/api/donations",donationRoutes);app.use("/api/finance",financeRoutes);app.use("/api/content",contentRoutes);app.use("/api/expenses",expenseRoutes);
app.use("/api/receipts",receiptRoutes);app.use("/api/audit-logs",auditLogRoutes);
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({message:err.message||"Server error"});});
connectDB().then(()=>app.listen(port,()=>console.log(`API: http://localhost:${port}`))).catch(e=>{console.error(e);process.exit(1)});